name: 💥 dnsx - DNS Resolver

on: [push]
    # schedule:
      # - cron: '0 0 * * *'
    # workflow_dispatch:

jobs:
  dnsx-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: 💥 dnsx - DNS Resolver
        uses: projectdiscovery/dnsx-action@main
        with:
          list: hosts.txt

      - name: test
        run: 
            dnsx -h 
         

      # - name: GitHub Workflow artifacts
        # uses: actions/upload-artifact@v2
        # with:
          # name: dnsx.log
          # path: dnsx.log
