name:   💥 dnsx - DNS Resolver
on: 
 [push]
    # schedule:
    #   - cron: '0 0 * * *'
    # workflow_dispatch:

jobs:
  dnsx-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: create hosts.txt
        run: |
            [ ! -x /home/runner/go/bin/dnsx ] && go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest

            
            # echo "/home/runner/go/bin/" >> $GITHUB_PATH
            #dnsx -h
            # wget https://raw.githubusercontent.com/JaveleyQAQ/checkCDN/main/baidu.com.domain
            # git clone https://github.com/JaveleyQAQ/checkCDN
            # ls
            # cd checkCDN 
            # chmod +x checkCDN
           #./checkCDN -file baidu.com.domain
          
      - uses: actions/upload-artifact@v4
        with:
            name: cdn_provider
            path: ${{ github.workspace }}/cdn_provider/*
