name:   💥 dnsx - DNS Resolver
on: 
 [push]
    # schedule:
    #   - cron: '0 0 * * *'
    # workflow_dispatch:

jobs:
  dnsx-scan:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: 1.17
      # - name: check GO ENV1
      #   run: ｜
      #    go env
         
      # - name: 💥 dnsx - DNS Resolver
      #   uses: projectdiscovery/dnsx-action@main
      #   with:
          # list: hosts.txt

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          curl www.google.com
          go env
          pwd
          ls ~/go
          
         
            
      # - uses: actions/upload-artifact@v4
      #   with:
      #       name: cdn_provider
      #       path: ${{ github.workspace }}/cdn_provider/*
